### ISSUE TITLE
T26 Kaavan ulkorajalla kaavamääräysryhmä, jolla yksi tai useampi yleismääräys

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#100]
Paikkatietoasiantuntijana haluan luoda koko kaavalle yhden tai useamman yleismääräyksen, koska se koskettaa koko kaavaa, jotta koko kaavalle voidaan antaa määräyksiä.
```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/7
```

**Comment by SannaJokela** [comment]
Osa tietomallia jo, suljen tämän

**Comment by SannaJokela** [comment]
Avaan, koska jos yleismääräyksiä on useampi pistetäänkö ne yhteen ryhmään?

**Comment by SannaJokela** [comment]
Samaan ryhmään, sovittu asia. Suljetaan
