### ISSUE TITLE
T43 Sama kaavamääräysryhmä usealle kaavakohteelle

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#107]
Paikkatietoasiantuntijana haluan tuottaa useammalle kaavakohteelle saman kaavamääräysryhmän kerralla, koska muuten työni hidastuu.

Osa QGISin perustoiminnallisuuksia. Huomioitava dokumentaatiossa

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/236
```

**Comment by SannaJokela** [comment]
Voi toteuttaa jo, suljetaan
