### ISSUE TITLE
Tietomallissa / QGIS-projektissa huomioitava, että voidaan viitata relaatiolla kohteesta toiseen

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#109]
Missä tapauksissa maakuntakaavoissa tarvitaan tätä? Onko vain spatiaalinen yhteys?

**Comment by SannaJokela** [comment]
Selvitettävä onko tämä maakuntakaavoissa oleellista

**Comment by SannaJokela** [comment]
Ei tarvita kaavoittajien mukaan
