### ISSUE TITLE
T38 Kehittämisperiaatemerkinnän luominen käyttötarkoituskohdistuksen avulla

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#115]
Paikkatietoasiantuntijana haluan tietää, miten luodaan kehittämisperiaate merkintä, jotta voin sellaisen tehdä, koska Katja-asetuksessa kehittämisperiaate tehdään käyttötarkoituskohdistuksena.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/116
```

**Comment by SannaJokela** [comment]
Sama kuin #84, suljetaan
