### ISSUE TITLE
T36 Ohjeet epämääräistä sijaintia koskevien kohteiden kaavamääräysten tuotantoon

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#118]
Paikkatietoasiantuntijana haluan tietää mihin kohdistetaan kaavamääräys, jonka kohteen sijainti on epämääräinen 

Esim. Aluekohtainen suunnittelumääräys: Salo-Lohjan ratalinjan teknisten ratkaisujen…, Kiskonjoen latvavesien alue, TP-alue - Vahdontien ja x-alueen sisään jäävä alue

, jotta voin toteuttaa kyseisen määräyksen nykyisellä järjestelmällä, koska aiemmin määräys on kirjattu yleismääräyksiin.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/119
```

**Comment by SannaJokela** [comment]
Edelleen näissä tapauksissa tiedot yleismääräyksiin tai tarkemmin muihin kohteisiin. Suljetaan.
