### ISSUE TITLE
T46 Lähtötiedoista valittujen kohteiden ja ominaisuustietojen vienti kaavatietomalliin ohjatusti

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#127]
Paikkatietoasiantuntijana haluan viedä useamman lähtötiedosta valitun kohteen kaavatietomalliin siten, että järjestelmä ohjaa tietojen vientiä, jotta kaikkia tietoja ei tarvitse täyttää useampaan kertaan, koska jos järjestelmä ei ohjaa tietojen vientiä, joudun täyttämään kaikki muut paitsi geometriatietoja käsin.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/129
```

**Comment by SannaJokela** [comment]
Käytännössä samaa kuin tämä, duplikaatti #121
