### ISSUE TITLE
T24 Lähtötietojen lajin liittäminen tietoihin

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#128]
Paikkatietoasiantuntijana haluan lisätä lähtötiedoista metatietoja, kuten lähtötietoaineiston lajin, koska näitä tietoja tarvitaan myöhemmin, jotta tiedot saadaan raportteihin.

Selvitettävää:

- [ ] Mitä eri lajeja lähtötiedoilla voi olla? (esim. "kansalliset lähteet, selvitykset, mitä muuta")

```[tasklist]
### Tasks
```

**Comment by SannaJokela** [comment]
Suljen tämän, koska asiakirjatyyppejä tietomallissa useita. Jos tarve, niin avataan uudelleen.

**Comment by SannaJokela** [comment]
Liittyikin lähtötietotauluun ei asiakirjatauluun, avataan

**Comment by SannaJokela** [comment]
Kysytty asiaa kaavoittajilta: ei lopulta ollutkaan tarvetta luokitella lähtötietoja
