### ISSUE TITLE
Sykelle laitettu kysymys värikoodista ja sen tarpeellisuudesta

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#133]
Värikoodia tarvitaan Syke-päässä, jos maakunnassa lisätään siihen jotain, voidaan Syke-päässä huomioida värikoodi mahdollisesti

**Comment by SannaJokela** [comment]
Vastaus: Ryhti-karttapalvelussa kaavat visualisoidaan KATJA-asetuksessa määritellyllä värityksellä. Jos mukana on värikoodi sitä voitanee käyttää visualisoinnissa ja KATJA-asetuksen värin sijaan. 

Tiedoksi @Rikuoja eli seuraavaksi kysytään haluaako kaavoittajat että siihen tallennetaan oma värikoodi...

**Comment by SannaJokela** [comment]
Ei ollut tarve laittaa omaa värikoodia maakuntakaavoittajilla, halutaanko poistaa se tietomallista vai pistetäänkö vaan niin, että ei vaan näytetä sitä edes QGISin puolella mitä sanoo @Rikuoja (lähinnä siis että tarviiko validoinnin vuoksi semmoinen olla jsonissa tms kenttänä)

**Comment by SannaJokela** [comment]
@rlindb huomioi QGIS-toteutuksessa, että vaikka datassa on kenttä värikoodille, sitä ei tarvita QGIS-projektissa - aiheuttaa vain hämmennystä.

**Comment by SannaJokela** [comment]
Suljen tämän, koska tätä kysytty ja vastaus on ettei kaavoittajille pakollinen.
