### ISSUE TITLE
Add additional date fields for lifecycle status events

### ISSUE THREAD

**Issue by Rikuoja** [GispoCoding/hame-ryhti#14]
Currently, kaava (and kaavamääräys and kaavakohde, if applicable) only have date fields for some events (e.g. creation date and valid_from date).

Probably will need to add dates for *all* plan lifecycle status events (draft, approval etc.) that we want to import to Ryhti. This is because Ryhti API requires each lifecycle status of the plan to be embedded within the corresponding decision making event (e.g. the date of approval of the plan must be provided when sending an approved plan to Ryhti API).

Will have to check which of these fields have to also be present in kaavamääräys and kaavakohde. Kaava will have to have all of these.

Perhaps kaavamääräys and kaavakohde will need them too, if e.g. the kaava is approved but at the same date (or another date) a single kohde or single määräys is cancelled or revoked in the court?

**Comment by SannaJokela** [comment]
@Rikuoja tää oli todo-listalla mutta ei assignattu - oliko sulla työn alla kuitenkin?

**Comment by Rikuoja** [comment]
@SannaJokela Ei ole työn alla, koska tässä on *kysymys*.

**Comment by SannaJokela** [comment]
@msorvoja https://koodistot.suomi.fi/codescheme;registryCode=rytj;schemeCode=kaavaelinkaari tuolla nuo kaikki tilat ja niille siis jokaiselle oma pvm-kenttä.

**Comment by msorvoja** [comment]
@SannaJokela Myös kaavasuosituksella on elinkaaritila eli se myös?

**Comment by SannaJokela** [comment]
@msorvoja aivan, kyllä. Jossain vaiheessa mietin että olisi melkeen parempi jos ryhmällä on, mutta ilmeisesti jokin yksittäinen kaavamääräys tai suositus voidaan kumota ja ryhmä jää (vaikka ehkä parempi olisi vaan tehdä uusi ryhmä). Mutta koitetaan tällä. Eli joo, suosituksella myös kaikki elinkaaritilat

**Comment by Rikuoja** [comment]
@SannaJokela @msorvoja

Koska näitä on niin paljon ja nyt kun kivasti kaikki tekstit on koodistoista tänne copypastetettu, niin nyt tulee mieleen speksata tätä tarkemmin. Eli paljon yksinkertaisempi tietokantarakenne olisi tehdä erillinen taulu, jossa on viittaukset elinkaaren tilaan ja kohteeseen jota elinkaaren tila koskee, sekä kyseisen elinkaaren tilan alkupäivämäärä.

![image](https://github.com/GispoCoding/hame-ryhti/assets/9367712/36047322-d99a-4bb4-b28f-41522f5a9aa5)
