### ISSUE TITLE
Huomioitava pakollisuus tietyissä elinkaaren vaiheissa eli ei voi välittää Ryhtiin jos asiakirja puuttuu. Miten tämä tehdään?

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#140]
Eli ei voi välittää Ryhtiin, jos tietyssä vaiheessa jokin asiakirja puuttuu. 

Suunniteltava validointisäännöt tietokantaa

**Comment by SannaJokela** [comment]
#41 osa validointisääntöjä, suljetaan tämä sillä tulee validoinnissa huomioitua
