### ISSUE TITLE
T28 Kaavakohteiden nimiöinti

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#143]
Paikkatietoasiantuntijana haluan luokitella kaavatasoja ominaisuustietojen mukaan, jotta voin visualisoida ja nimiöidä niitä haluamallani tavalla, koska haluan tuottaa kartografisesti miellyttävän tuotteen. Ks. myös #103 

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/112
```

**Comment by SannaJokela** [comment]
Yhdistetty #146
