### ISSUE TITLE
Syken kanssa keskusteluun miten hoidetaan selkokielisyys ja rakenteellisuus

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#149]
Legenda rakenteisesti voi olla kapulakieltä. Tarvitaan ohjeistusta

```[tasklist]
### Tasks
- [x] kysy asiaa Sykeltä, ei vielä tiedossa ratkaisua
```

**Comment by SannaJokela** [comment]
Sovittu asiakkaan kanssa, että käytetään kuitenkin tekstiarvoa/sanallista määräystä vaikka rakenteellistettu tietoa. Käytetään legendassa selkokielistä versiota
