### ISSUE TITLE
T17 Karttaselitteen muokkaamisen mahdollistaminen siten, että tiedot muuttuvat myös tietokannassa 

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#150]
Tätä ei välttämättä teknisesti voida estää, huomioitava ohjeistuksessa

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/112
```

**Comment by SannaJokela** [comment]
Ei mahdollista toteuttaa, aina voi säätää selitettä mihin suuntaan tahansa. Pitää asiantuntijan ymmärtää asia. Suljen tämän.
