### ISSUE TITLE
T79 Lainvoimaisesta kaavasta voimassaolevaan automaattisesti Ryhtissä

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#164]
Tietojärjestelmäkehittäjänä haluan tietää hoituuko Ryhti-järjestelmässä lainvoimaisesta kaavasta siirtyminen voimassaolevaan automaattisesti, jotta ohjeistus ja järjestelmäkehitys voidaan toteuttaa sen perusteella, koska tämä asia on nyt epäselvää.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/165
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/166
```

**Comment by SannaJokela** [comment]
Ohjeissa alatehtävässä oli että Ryhti hoitaa
