### ISSUE TITLE
Selvitettävä, hoituuko Lainvoimainen/Voimassa- elinkaaritilan muutos automaattisesti Ryhti-päässä

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#165]

**Comment by SannaJokela** [comment]
@rlindb eikös tästä ollut joku dokumentti, mun mielestä se siirtyi suoraan voimaan tyyliin 2 viikon sisään.

**Comment by SannaJokela** [comment]
Ryhti-järjestelmä ilmeisesti generoi tämän https://ryhti.syke.fi/alueidenkaytto/tietomallimuotoinen-kaavoitus/kaavatietomallin-elinkaari-ja-laatusaannot/, suljetaan tämä ja avataan jos tarvitaan jotain vielä.
