### ISSUE TITLE
T44 Kaavatietojen vienti Ryhtiin, kun kaava on hylätty, kumottu tai valitettu

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#169]
Paikkatietoasiantuntijana haluan viedä kaavatiedot Ryhti-järjestelmään myös, jos kaava on hylätty, kumottu tai siitä on valitettu, koska muuten Ryhti-järjestelmässä ei ole tätä tietoa, jotta loppukäyttäjällä on saatavilla oikea tilanne.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/171
```

**Comment by SannaJokela** [comment]
Duplikaatti #158
