### ISSUE TITLE
Tietokannan omiin laatusääntöihin mm. Topologia - ja sisältövirheiden huomautukset, että validoidaan tiedot jo ennen validointipalveluun vientiä.

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#175]
Ks. laatusäännöt Ryhdin sivuilta

Selvitettävä mitkä PostGIS ja QGIS-puolelle. QGIS-puolelle tehtävät voi tehdä tässä issuessa, tietokantavalidoinnista on teknistä pohdintaa erikseen alla. ==> sovittu että validointiasiat tehdään tietokannan/sovelluksen puolella.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/41
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/253
```

**Comment by SannaJokela** [comment]
Käyty läpi validointisäännöt ja lähetetty Sykelle kysymyksiä.

**Comment by SannaJokela** [comment]
Suljetaan tämä ja jatketaan #41 puolella
