### ISSUE TITLE
T03 Jos ei järjestelmää, tietojen vienti käsin Ryhtiin

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#185]
Maakunnan virallisena tahona haluan, että Ryhtiin tunnistautuminen hoituu Ryhtin selainpalvelussa, jotta voin viedä itse käsin tiedot Ryhti-järjestelmään, koska minulla ei ole järjestelmää, josta työn voisi tehdä automaattisesti.

Toteutetaan ohjeistuksessa jos tarpeen

```[tasklist]
### Tasks
```

**Comment by SannaJokela** [comment]
Ei mahdollista tehdä käsin, suljetaan.
