### ISSUE TITLE
Suunniteltava, mitä GeoTIFF sisältää yhdessä kaavoittajien kanssa.

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#187]
GeoTiffissä ei saa olla mukana legendaa
Perinteisen kaavakartan näköinen, mutta vain GeoTIFF-muodossa (juuri sen näköinen kuin maakunta on kaavoista päättänyt=
Jos vaihemaakuntakaava, vanhan kaavan alueet läpinäkyvinä
Mittakaavaerojen takia voi tulla jännittäviä tuloksia Ryhti-päässä, mutta sille ei voida mitään.

Tiedot pitää toimittaa Ryhtiin- ehdotus-, hyväksymis- ja muutoksenhaku sekä voimaantulovaiheissa.

```[tasklist]
### Tasks
- [x] kysytty Sykeltä onko tähän speksejä olemassa
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/248
```
Milloin GeoTIFF viedään ryhtiin eli mitkä pakolliset vaiheet?

**Comment by SannaJokela** [comment]
Huomio speksit: [Kaavakartan GeoTIFF-vaatimukset - Ryhti (syke.fi)](https://ryhti.syke.fi/alueidenkaytto/tietomallimuotoinen-kaavoitus/kaavatietomallin-elinkaari-ja-laatusaannot/kaavakartan-geotiff-vaatimukset/)

**Comment by SannaJokela** [comment]
Kysytty kommentteja, tehdään speksien mukaan.
