### ISSUE TITLE
GeoTIFFin käsittely

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#188]
Käytännössä: kaavoittaja luo QGISistä GeoTIFFin sellaisena kuin hän haluaa sen olevan, GeoTIFF tallennetaan websivuille, josta se lisätään rajapintaan ja sitä kautta Ryhtiin. Käytännössä aina kun viedään tietoja Ryhtiin, toimitetaan myös GeoTIFF.

Toteutukseen:

- [ ] QGISillä GeoTIFF esim. kaavan extentistä talteen
- [ ] GeoTIFF websivuille, josta URL Asiakirjatauluun

Ohjeita:

Rasterit PostGISiin plugari? https://plugins.qgis.org/plugins/raster2postgis/

https://gis.stackexchange.com/questions/247417/creating-a-geotiff-from-postgis-raster-column 

https://gist.github.com/arthur-e/6222249

**Comment by SannaJokela** [comment]
@annijus voisit tätä pohtia myös kesän aikana

**Comment by LKajan** [comment]
Kirjoitin tiedostojen tallentamisesta tietokantaan tänne: https://github.com/GispoCoding/hame-ryhti/issues/186#issuecomment-2160763350

Lyhyesti, ei suositella. Jos silti tarve, niin tallennus `bytea`-kenttään ei PostGIS-rasterina.

**Comment by SannaJokela** [comment]
Päivitin työnkulkua, ei tallenneta GeoTIFFiä tietokantaan vaan käsitellään samaan tapaan kuin muut asiakirjat.
