### ISSUE TITLE
T69 Kaavalle pysyvä kaavatunnus Ryhtistä

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#190]
Paikkatietoasiantuntijana haluan, että Ryhti-järjestelmä antaa kaavalle pysyvän kaavatunnuksen, jotta voin liittää sen käsin tai automaattisesti kaavan tietoihin, koska näin kaava saa uniikin pysyvän tunnuksen.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/239
```

**Comment by Rikuoja** [comment]
Toteutettu.

Saadaan käyttöön konfiguroimalla asiakkaan palveluväyläyhteys kuntoon.
