### ISSUE TITLE
T18 Kaavatietojen manuaalitarkistus vanhojen kaavojen importoinnin jälkeen

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#204]
Paikkatietoasiantuntijana haluan käydä automatisoidusti viedyt tiedot läpi, jotta niissä ei ole virheitä, koska kaikki tieto ei ole ollut täysin rakenteellista HAME-mallissa tai sitä voidaan tulkita eri tavalla sillä koodilistat ovat erilaisia.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/240
```

**Comment by SannaJokela** [comment]
HAME-kaavoja ei voikaan viedä ryhtiin ilman niiden uudelleenhyväksymistä
