### ISSUE TITLE
T06 Ei viedä Ryhtiin muuta kuin voimassaolevat tiedot vanhoista kaavoista

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#205]
Paikkatietoasiantuntija ei vie Ryhti-järjestelmään asti vanhoissa kaavoissa olevia kumottuja tietoja, jotta Ryhti-järjestelmässä on vain voimassaolevat tiedot, koska muuten kumoamisesta jouduttaisiin tekemään uusi vienti.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/236
```

**Comment by SannaJokela** [comment]
Suljettu, koska ei viedä ryhtiin vanhoja tietoja.
