### ISSUE TITLE
T14 Kaksikielisyyden viranomaisvelvoitteiden täyttyminen

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#213]
Paikkatietoasiantuntijana haluan että tietokantaan tallentuvat tiedot suomeksi ja ruotsiksi, koska osa maakuntakaavoista on kaksikielisiä, jotta viranomaisvelvoitteet täyttyvät.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/7
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/8
```

**Comment by SannaJokela** [comment]
@rlindb tähän liittynee myös tietokannan kieliversiotuki, oliko se omana issuena/tehty??

**Comment by SannaJokela** [comment]
Tietokannassa huomioitu
