### ISSUE TITLE
Paluusanoman käsittely - kaava-asia

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/hame-ryhti#239]
Ryhti-tunnus haetaan automaattisesti palveluväylän kautta ja tallennetaan kaavalle silloin kun kaavoittaja haluaa.

Tämän jälkeen kaava-asian voi validoida ja lähettää. En tiedä tuleeko onnistuneen kaava-asian lähetyksen vastauksena sitten jotain muutakin, joka myös pitäisi tallentaa.

Ainakin jos kaava-asian lähettäminen epäonnistuu (eli kaava-asian validointi ei onnistu), pitää myös tallentaa kaava-asiassa (esim. päivämäärissä) tulleet virheet tietokantaan käyttäjälle tiedoksi.

**Comment by Rikuoja** [comment]
Toteutettu jo
