### ISSUE TITLE
Lähtötietoihin valmiiksi hallinnolliset rajat.

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#24]
QGIS työtilaan voisi tuoda valmiiksi MML:n rajapinnat joissa hallinnolliset rajat eri mittakaavatasoilla. 

Hallinnolliset rajat joita ainakin tarvitaan: kunnat, maakuntarajat.

Tietokantaan tarvitaan hallinnolliset rajat, jotta voidaan toteuttaa validointisääntö.

Kysytty Sykeltä mikä mittakaavan kuntaraja on käytössä, ei vielä vastattu 14.5.2024

**Comment by Rikuoja** [comment]
- Mitä hallinnollisia rajoja tarvitaan? Maakunnat, kunnat?
- Tarvitaanko hallinnollisia rajoja tietokantaan? Eli halutaanko esim. että maakuntakaava voi olla vain yhden maakunnan alueella, tai muita tietokantarajoituksia? Jos ei tarvita, ne voivat olla myös vain QGIS-projektissa.

**Comment by SannaJokela** [comment]
Tarvitaan tietokantaan, sillä liittyy validointisääntöön

**Comment by msorvoja** [comment]
Lisätään hallinnollisen alueen koodilistaan maakuntien aluerajojen geometriat.

**Comment by rlindb** [comment]
https://www.maanmittauslaitos.fi/rajapinnat/paikkatiedot
