### ISSUE TITLE
Luo skripti, jolla saa luotua ssh-tunnelin helposti

### ISSUE THREAD

**Issue by lehtojaa** [GispoCoding/hame-ryhti#250]
- Luodaan skripti, jonka kuvaketta klikkaamalla luodaan tunneli tietokantapalvelimelle.
  - ensisijaisesti varmaankin vain Windows-ympäristöön: batch script (.bat)?
 - SSH-avainpari on silti kunkin luotava ja toimitettava. Ohjeistetaan avaimen nimeäminen yhtenäiseksi
   - Jokin projektiin liittyvä nimi? (defaulttina tulee algoritmin nimi)
 - Miten yhteysparametrit mukaan?
   - skriptin sisällä?
   - (konfiguraatio-tiedostosta?)
   - (komentorivi-parametrinä?)
   - (ympäristömuuttujina?)
   - Joku muu, mikä?
- Muutettava/lisättävä README:n nykyistä ohjeistusta

**Comment by lehtojaa** [comment]
Tai ehkä noiden parametri- ym. kysymysten pohjalta, voisi muuttaa skriptin ihan suoritettavaksi tiedostoksi (.exe)?

**Comment by Rikuoja** [comment]
Tehty.
