### ISSUE TITLE
Lisää tietokantaan mahdollisesti puuttuvia kenttiä

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#264]
Puuttuvia kenttiä/epäselvyyksiä kentissä:
**Kaavakohde:** 

- [x] - mittayksikkö (ei lisätä)
- [x] - kohteen kuvaus? onko sama kuin nimi? (ei ole, kuvaus on description, lisätään #265 :ssä)

**Kaavakohteen kaavamääräys**

- [x] - Aihetunniste (Sanna kysyy onko oikea asiasana)
Näyttää siltä, että kaavatietomallissa on myös ihan oikea asiasana-käsite (joka viittaa johonkin asiasanastoon). Käytetäänkö kaavatietomallin asiasana- ja asiasanasto-käsitteitä, vai käytetäänkö vain asiasanaa, joka viittaa suomalaiseen ontologiaan? Kummassakin tapauksessa pitää lisätä tietokantaan omia tauluja, joihin tuodaan aihepiiriin liittyvä asiasanasto, tai joku yleinen suomalainen ontologia, halutaanko tätä? https://tietomallit.suomi.fi/model/rytj-kaava/Asiasana/45116f50-3e7d-4491-9e22-4fa4fad3a7ea ==> aihetunniste ei ole asiasanasto vaan ihan mikä vain asiasana, päätetty että otsikko toimii hame-ryhti-kannassa aihetunnistetta vastaavana elementtinä
- [ ] - Name? Mikä tämä on? Onko aihetunniste vai jokin muu (Otsikko, tämä on vaihtoehto asiasanalle jos ei ole oikeaa asiasanoitusta)

**Kaavamääräysryhmä**

- [x] - Värikoodi, lisätäänkö kaavatietomallissa luki
![image](https://github.com/GispoCoding/hame-ryhti/assets/158172654/ca7ee36a-bdd9-46cb-b339-7fd3d172f20c) ==> ei lisätä, ei tarvita missään

**Kaavakohteen kaavasuositus**

- [ ] nimi? mikä se on? (outoa ettei suosituksella olisi otsikkoa/asiasanaa. Halutaanko varmasti että suosituksista puuttuu näitä tunnistekenttiä jotka on määräyksissä?)

**Asiakirjat** 

- [x] - UUID (puuttui, lisätään #265 ssä)

**Comment by rlindb** [comment]
@Rikuoja tällaisia puutteita löysin, kun kävin tauluja läpi. Osa noista on sellaisia, että ei ehkä ole puutteita vaan kaipaan tietoa, mitä ne namet esim. on.

**Comment by Rikuoja** [comment]
Nimi on aina "name". Silloin kun noita tehtiin, tietomallissa oli minusta vielä määräyksen nimi/otsikko, en muista aihetunnisteesta kuulleeni joten ehkä tietomalli on muuttunut.

Kaavakohteen kuvaus on pitempi kuvausteksti, lisään sen.

**Comment by Rikuoja** [comment]
Kas, tietomallissahan lukee yhä että "tarvitaan ehkä vielä otsikko tai joku muu erottava asia".

Nimi/otsikko on siis tietokannassa aina "name".

**Comment by SannaJokela** [comment]
@rlindb onkohan tää tehtävä jo tehty?
