### ISSUE TITLE
Suunnittele, miten QGIS-projekti tallennetaan tietokantaan

### ISSUE THREAD

**Issue by Rikuoja** [GispoCoding/hame-ryhti#27]
Master QGIS-projekti olisi kaikilla saatavilla tietokannassa - ei oikeuksia kaavoittajilla muokata.
Mutta omaa QGIS-projektia voisi muokata (omia tasoja voi tuoda). 

==> miten hoidetaan migraatioasiat?

Master voisi olla GitHubissa tai kannassa siten, että ei pääse muokkaamaan.
Kuka päivittää masteria?
Miten ohjeistetaan kaavoittajia?

**Comment by SannaJokela** [comment]
Mitä muuta ajatuksia tässä on kuin vaan tallentaa QGIS PostGIS-tietokantaan? Tarkoitetaanko että olisi eri versioita/maakuntaliitto?

**Comment by SannaJokela** [comment]
Samantyyppinen kuin #21

**Comment by SannaJokela** [comment]
publiciin master QGIS-projekti.
