### ISSUE TITLE
QGIS-projektin parannusehdotukset testipäivän perusteella

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/hame-ryhti#288]
- [x] Toimijan lisäyksessä y-tunnukseen ei voi jättää NULL, sillä se on pakollinen ja ei voi jättää myöskään tyhjäksi ==> ohjeistettava
- [x] Maanpäällinen defaultisti ekaksi
- [x] Pakolliset tiedot tauluissa ensin täytettäväksi
- [x] Pakolliseksi + kentän nimen yhteyteen tieto, että kaavamerkintä-taulun kirjaintunnusta käytetään identifiointiin
- [x] Geometrioiden kautta mahdollista lisätä kaavamerkintöjä
- [x] Geometriatasoille nimi ja kuvaus-kentät listalla alimmaksi

**Comment by SannaJokela** [comment]
@rlindb oliko kaikki tehty tästä?

**Comment by rlindb** [comment]
@SannaJokela ei ole. Maanpäällinen puuttuu

**Comment by SannaJokela** [comment]
@rlindb joko tuo maanpäällinen on hoidettu?

**Comment by rlindb** [comment]
nyt on.
