### ISSUE TITLE
Multigeometriat ei validaattorista läpi, jos vain yksi kohde per feature

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/hame-ryhti#312]
Tehtävä triggeri joka muuttaa tarpeen vaatiessa (=kun kohteita on vain yksi per feature) multigeometriat singleksi.

**Comment by msorvoja** [comment]
SYKEn päivitys korjannut virheen

**Comment by msorvoja** [comment]
Kokellaan muuttaa kaikki multigeometriat single-tyyppisiksi geometrioiksi
