### ISSUE TITLE
Paikkatietoasiantuntijana haluan tuottaa useammalle kaavakohteelle saman kaavamääräyksen kerralla, koska muuten työni hidastuu, jotta pääsen helpommalla.

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#37]
Tarkoittaa että käyttäjä voi valita 10 kohdetta ja liittää niille kaavamääräsryhmän. QGISin perustioiminnallisuudet tekevät tämän QGIS-projektin luonnin myötä.

**Comment by Rikuoja** [comment]
Tarkoittaako tämä kaavamääräysryhmiä?

Vai tarkoittaako tämä sitä, että lisäksi myös yksittäisiä määräyksiä pitäisi voida lisätä suoraan kohteelle? Jälkimmäinen ominaisuus on kaiketi vielä harkinnassa.

**Comment by SannaJokela** [comment]
Kommentoitu ylle.
