### ISSUE TITLE
T50 Kohdekohtaisen kaavamääräysryhmän huomioiminen

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#38]
Paikkatietoasiantuntijana haluan luoda joillekin kaavakohteille hieman poikkeavan kaavamääräyksen vaikka niiden otsikko olisikin sama, koska määräys voi olla kohdekohtainen, jotta kaavaselitteessä visualisointi pysyy samana.
```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/79
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/80
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/81
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/82
```

**Comment by Rikuoja** [comment]
Tähänkin on tosiaan kaksi tapaa:

1) kopioidaan kaavamääräysryhmiä, mutta pidetään visualisointi samana, TAI
2) sallitaan yksittäisten määräysten lisääminen ryhmän ohella. Tällöin ryhmän määräysten LISÄKSI kohteella on ylimääräinen määräys, mutta visualisointi on silti ryhmän mukainen.

Kumpikin tapa on mahdollinen. Toteutetaanko kumpikin vaihtoehto?

**Comment by Rikuoja** [comment]
Sama kysymys toteutustavasta on myös tarinassa https://github.com/GispoCoding/hame-ryhti/issues/37

**Comment by SannaJokela** [comment]
Sovittu että tätä ei toteuteta
