### ISSUE TITLE
Add koodisto tables

### ISSUE THREAD

**Issue by Rikuoja** [GispoCoding/hame-ryhti#4]
Add tables for those RYTJ koodistot that we use in maakuntakaavat. This is needed before we can implement #2

**Comment by Rikuoja** [comment]
Also, add all required code table columns.

Think about how to represent hierarchical data, do we need e.g. Postgres Ltree or something similar??

**Comment by SannaJokela** [comment]
Take also into account, that we have own codes for Asiakirjatyyppi in Mkaavatietomalli-ryhmät.draw-io.

**Comment by SannaJokela** [comment]
The planners said that they don't need the English versions of the codelists.
