### ISSUE TITLE
T05 Filegeodatabase PostGIS-kantaan

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#49]
Lounaistiedon ylläpitäjänä haluan viedä Filegeodatabase-muotoisen tiedoston Lounaistiedon PostGIS-tietokantaan, koska sieltä voidaan tehdä Paikkatietoasiantuntijalle GeoJson-muotoinen tiedonsiirtoformaatti, jotta Paikkatietoasiantuntija voi viedä sen käsin Ryhtiin tai valtuuttaa minut tekemään työn.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/50
```

```[tasklist]
### Tasks
```

**Comment by SannaJokela** [comment]
Duplikaatti #51
