### ISSUE TITLE
Add other tables to PostGIS 

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/hame-ryhti#6]
Add other tables with no geometry to PostGIS according to Mkaavatietomalli-ryhmät.drawio

Asiakirjat
Lähtötietoaineistot
Toimija
Kaavasuositus
Kaavamääräys
Kaavamääräyryhmä: check new values on Ryhmätyyppi

**Comment by Rikuoja** [comment]
Should Kaavamääräysryhmä get a better name? E.g. Kaavamerkintä? (ryhmätyyppi = merkintätyyppi?)

**Comment by Rikuoja** [comment]
NOT completed

**Comment by Rikuoja** [comment]
The tables are there. Some koodistot are missing/not complete, so there are separate issues created for them.
