### ISSUE TITLE
T23 Kaavan ulkorajan ominaisuustiedot

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#63]
Paikkatietoasiantuntijana haluan lisätä Kaavan ulkorajalle tiettyjä ominaisuustietoja, kuten nimen ja maakuntakohtaisen tunnuksen ja kaavalajin alasvetovalikosta.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/24
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/25
```

**Comment by SannaJokela** [comment]
Toteutettu kantaan
