### ISSUE TITLE
T52 Eri kaavaprosessien tietojen hallinta tietokannassa

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#64]
Paikkatietoasiantuntijana haluan, että eri kaavojen tiedot on talletettu eri kansioihin, jotta ne eivät mene sekaisin, koska kaavaprosesseja voi vuosien aikana tulla useita.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/65
```

**Comment by SannaJokela** [comment]
Duplikaatti #65
