### ISSUE TITLE
T13 Kaavan luonnosvaiheista voi tehdä useita versioita

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#66]
Paikkatietoasiantuntijana haluan että kaavan luonnosvaiheista on mahdollista lisätä tietokantaan useita versioita, jotta niitä voidaan työstää eteenpäin tarvittaessa, koska luonnosvaiheen vaihtoehtoja voi kaavasta olla useita.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/67
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/69
```

**Comment by SannaJokela** [comment]
Yhdistetty #65
