### ISSUE TITLE
Build a QGIS project in finnish

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#7]
- use Ryhti.gpkg as a model and check the user requirements gathered from regional land use planners

- layers and project should be in EUREF_FIN eli epsg 3067
- make codelists uneditable: [check instructions](https://gis.stackexchange.com/questions/351784/is-it-possible-to-disable-editing-for-certain-layers-in-a-qgis-project#:~:text=Open%20Project%20properties%20%3E%20Data%20sources,want%20to%20make%20not%20editable.)
- make layers unremovable so that the user can not delete them 
<img width="744" alt="image" src="https://github.com/GispoCoding/hame-ryhti/assets/23258285/0b6ab290-9ef4-40b6-ad43-835eeba03a14">

**Comment by Rikuoja** [comment]
Here gpkg is probably not used, if we save the QGIS project to PostGIS database?

Layers should come directly from database, so they have the right projection, but the project settings should be checked so it uses the same.

**Comment by SannaJokela** [comment]
Tämä tehty, pienet fiksit erikseen issueiksi jos tarvetta
