### ISSUE TITLE
Selvitettävä miten kohdekohtainen kaavamääräysryhmä käsitellään

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#79]
Kysytään kaavoittajilta miten halutaan käsitellä ryhmä.

Jos kyllä, toteutetaan tietomalliin suora yhteys kaavakohteen ja määräyksen välillä silloin kun käyttäjä on lisännyt ryhmän + kaavakohtaisen lisämääräyksen.

**Comment by SannaJokela** [comment]
5.3. fiilis on ettei tarvita tätä, katsotaan myöhemmin

**Comment by SannaJokela** [comment]
Suljen tämän koska ei tulut tästä vastustusta, jos pitää muuttaa niin avataan sitten.
