### ISSUE TITLE
Kehitetään QGIS-projektia jos kohdekohtainen kaavamääräysryhmä huomioidaan

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#81]
Kohdekohtaisuus erotellaan esim. hieman eroavalla kirjanintunnuksella. 

Esim. Otsikko: Teollisuusalue, Kirjainmerkintä: T ja Otsikko: Teollisuusalue, Kirjainmerkintä T-1 ovat eri kaavamääräysryhmiä, mutta visualisoinnissa kaavoittaja voi visualisoida ne saman luokittelun alle otsikon: Teollisuusalue perusteella. Legendan tekstiosiossa voidaan ryhmitellä sisällöt niin, että eri kirjainmerkinnän omaaville osioille laitetaan oma kappale mukaan. Esim. jotenkin seuraavasti: 

Teollisuusalue (otsikko)
Täällä saa tehdä teollisuutta.
(If-lause jotenkin näin: IF kirjaintunnus eroaa toisista otsikko Teollisuusalue kirjaintunnuksista add kirjaintunnus): Huom! [T-1]: "Tällä kohteella hieman poikkeava määräys kuin muilla teollisuusalueilla."

**Comment by SannaJokela** [comment]
Huomioitava legendan teossa mahdollisesti.

**Comment by SannaJokela** [comment]
Sovittu testauksessa että tätä ei tarvitse huomioida
