### ISSUE TITLE
Selvitä miten tekstimuotoinen määräys kirjataan tekstiarvona vai sanallisena määräyksenä.

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#88]
**Taustaa:** Katja-asetuksen ensimmäisessä versiossa viitataan, että sanalliset määräykset tehdään aina esim. kehittämisperiaatteille, mutta ei aluevarauksille. Kirjataanko tekstimuotoiset sisällöt siis aluevarausten osalta tekstiarvona, mutta kehittämisperiaatetyyppisille merkinnöille sanallisena määräyslajina, jolle annetaan tekstiarvo ja edelleen sanallisen määräyksen laji. 

**Esimerkki: Matkailupalvelun kohteelle**

_**Gispon ehdotus:**_ 
Kaavamääräyksen kaavamääräyslaji “MatkailupalvelujenAlue”
tekstiarvo: “Merkinnällä osoitetaan seudullisesti merkittäviä matkailupalveluiden alueita, kuten matkailu- ja lomakeskuksia, lomakyliä, leirintäalueita tai muita vastaavia matkailua ja majoitusta palvelevia toimintoja”. 
Lisätiedonlaji “Pääkäyttötarkoitus”.  

_**Katja-asetuksen mukaan**_
Kaavamääräyksen kaavamääräyslaji “MatkailupalvelujenAlue”
Lisätiedonlaji “Pääkäyttötarkoitus”.  
Ei tietoa mihin teksti laitetaan?

**Toinen esimerkki: Matkailun vetovoima-alue ja matkailun ja virkistyksen kehittämisen kohdealue**

_Gispon ehdotus:_

Ensimmäisen kaavamääräyksen kaavamääräyslaji: matkailupalvelujenAlue
tekstiarvo: “Kulttuuriperintö-, maisema- ja luontoarvoja tulee vaalia matkailun vetovoimatekijöinä”
lisätiedonlajiksi “Osa-alue”. 

Toisen kaavamääräyksen kaavamääräyslaji: Virkistysalue-koodi
lisätiedonlajiksi “Osa-alue”. 

Kolmannen kaavamääräyksen kaavamääräyslaji: Kehittamisalue
tekstiarvo: “Aluetta tulee kehittää matkailupalvelukohteiden, maaseutumatkailun, palvelujen ja reitistöjen yhteistoiminnallisena kokonaisuutena alueen pääkäyttötarkoitusten kanssa yhteen sopivalla tavalla.”
lisätiedonlajiksi “Osa-alue”. 

_Katja-asetuksen mukaan:_

Ensimmäisen kaavamääräyksen kaavamääräyslaji on Kehittämisvyöhyke
Lisätiedonlaji: “Osa-alue”
Lisätiedonlaji: “Käyttötarkoituskohdistus” ==> Kaavamääräyslajikoodistosta “Matkailupalveluiden alue”
Lisätiedonlaji: “Käyttötarkoituskohdistus” ==>Kaavamääräyslajikoodistosta “Virkistysalue”

Toisen Kaavamääräyksen kaavamääräyslaji on Sanallinen määräys
Sanallinen määräyksen laji: ?
Tekstiarvo?: 

```[tasklist]
### Tasks
- [x] Kysytty Sykeltä, mutta ei vastausta
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/269
```

**Comment by SannaJokela** [comment]
Tietoa 4.4.2024:

"Toimenpiderajoitus koodi ollaan siirtämässä sanallisen määräyksen alalajiksi, jolloin siihen tulee aina liittää tekstiarvo. Tämän hetkinen ajatus on ettei muille kaavamääräyslajeille kuin sanallinen määräys ja sen alakoodeille voi laittaa tekstiarvoa."

Sanallisen määräyksen koodi tarvitaan koska tekstissä voi olla asioita jotka ei liity kaavamääräyslajiin (esim. Teollisuusalue-kaavamääräysryhmän sanallisen määräyksen arvossa puhutaan virkistysarvoista)
