### ISSUE TITLE
T30 Ohjeet kaavan tuotantoon

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#91]
Paikkatietoasiantuntijana haluan ohjeet tietojen tuotannosta, jotta työni olisi helppoa, koska siirtymä vaatii opettelua.

Paikkatietoasiantuntijana haluan ohjeet siitä, miten eri elinkaaren vaiheiden tiedot tallennetaan ja miten niihin pääsee käsiksi myöhemmin.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/231
```

**Comment by SannaJokela** [comment]
Duplikaatti #236
