### ISSUE TITLE
Lisätiedonlaji koodilistan luonti maakuntakaavoittajien tarpeisiin

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#94]
https://koodistot.suomi.fi/codescheme;registryCode=rytj;schemeCode=RY_Kaavamaarayksen_Lisatiedonlaji suunniteltu maakuntakaavoittajien tietomallissa siten, että yhden otsikon alta voi valita vain yhden koodin. Eroaa kansallisesta tietomallista. 
```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/93
```

**Comment by SannaJokela** [comment]
Tämä on jo tehty ymmärtääkseni, eikö @Rikuoja eli siis lisätiedonlajikoodisto maakuntakaavoittajille erikseen?

**Comment by Rikuoja** [comment]
@SannaJokela Ei ole tehty, koska koodilistaa odoteltiin. Löysin nyt kolme github-issueta/käyttäjätarinaa, lisäsin niihin *kaikkiin* tuon tietokantatehtävän, jossa nuo tehdään, eli #15

**Comment by SannaJokela** [comment]
#15 duplikaatti, suljetaan
